### ISSUE TITLE
Failed to activate the formatter-json package

### ISSUE THREAD

**Issue by AaronAsAChimp** [gouvinb/formatter-json#1]
[Enter steps to reproduce below:]
1. Install formatter-json in Atom v1.11.0

**Atom Version**: 1.11.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [formatter-json](https://github.com/gouvinb/formatter-json) package, v1.0.1
### Stack Trace

Failed to activate the formatter-json package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at Module.consumeFormatter (/Users/aaronspaulding/.atom/packages/formatter/lib/main.coffee:70:21)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:355:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:779:28
```
### Config

``` json
{
  "core": {
    "telemetryConsent": "no",
    "useCustomTitleBar": true
  }
}
```

**Comment by rejhgadellaabsl** [comment]
+1

**Comment by JoyJava** [comment]
+1

**Comment by forivall** [comment]
Caused by https://github.com/atom-community/formatter/issues/7
